#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

!/bin/sh

read ref name remote_ref remote_name

if test "$ref" = refs/heads/master; then
    echo ---------------------------------------------------
    echo ERROR: Not allowed to push directly to main branch.>&2
    echo ---------------------------------------------------
    exit 1
fi

yarn build
