version: "3.9"

services:
    database:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"

    backend:
        depends_on:
            - "database"
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: always

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile

        ports:
            - "3000:3000"
        restart: always
