// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: ingredients.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients(id, name, category_id)
VALUES ($1, $2, $3)
RETURNING id, name, category_id, createdat, createdby, deleted
`

type CreateIngredientParams struct {
	ID         uuid.UUID
	Name       string
	CategoryID uuid.UUID
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, createIngredient, arg.ID, arg.Name, arg.CategoryID)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Createdat,
		&i.Createdby,
		&i.Deleted,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :one
UPDATE ingredients
SET deleted = true
WHERE id = $1
RETURNING id, name, category_id, createdat, createdby, deleted
`

func (q *Queries) DeleteIngredient(ctx context.Context, id uuid.UUID) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, deleteIngredient, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Createdat,
		&i.Createdby,
		&i.Deleted,
	)
	return i, err
}

const getAllIngredients = `-- name: GetAllIngredients :many
SELECT 
	ingredients.id, 
	ingredients.name, 
	categories.name AS category_name,
	categories.id AS category_id 
FROM 
	ingredients
LEFT JOIN 
	categories 
ON categories.id = ingredients.category_id
WHERE 
	ingredients.deleted = false
ORDER BY 
	ingredients.createdat DESC
`

type GetAllIngredientsRow struct {
	ID           uuid.UUID
	Name         string
	CategoryName sql.NullString
	CategoryID   uuid.NullUUID
}

func (q *Queries) GetAllIngredients(ctx context.Context) ([]GetAllIngredientsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllIngredientsRow
	for rows.Next() {
		var i GetAllIngredientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryName,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIngredientById = `-- name: GetIngredientById :one
SELECT id, name, category_id, createdat, createdby, deleted FROM ingredients 
WHERE id = $1
`

func (q *Queries) GetIngredientById(ctx context.Context, id uuid.UUID) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, getIngredientById, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Createdat,
		&i.Createdby,
		&i.Deleted,
	)
	return i, err
}

const updateIngredient = `-- name: UpdateIngredient :one
UPDATE ingredients
SET id = $1, name = $2, category_id = $3
WHERE id = $1
RETURNING id, name, category_id, createdat, createdby, deleted
`

type UpdateIngredientParams struct {
	ID         uuid.UUID
	Name       string
	CategoryID uuid.UUID
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, updateIngredient, arg.ID, arg.Name, arg.CategoryID)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Createdat,
		&i.Createdby,
		&i.Deleted,
	)
	return i, err
}
