name: Munchies Deployment Pipeline
on:
    push:
        branches:
            - main
jobs:
    push_docker_images:
        name: Push Docker images to Dockerhub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push API
              uses: docker/build-push-action@v5
              with:
                  context: ./
                  file: ./backend/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/munchies-api:latest
